In [1]:
from gurobipy import GRB, Model, quicksum
import gurobipy as gb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker

In [2]:
blending_materials = pd.read_csv('https://raw.githubusercontent.com/Dhanvi199/schulich_data_science/refs/heads/main/blending_materials.csv')
blending_blends = pd.read_csv('https://raw.githubusercontent.com/Dhanvi199/schulich_data_science/refs/heads/main/blending_blends.csv')
welders = pd.read_csv('https://raw.githubusercontent.com/Dhanvi199/schulich_data_science/refs/heads/main/welders_data.csv')
welders_speed_data = pd.read_csv('https://raw.githubusercontent.com/Dhanvi199/schulich_data_science/refs/heads/main/welders_speed_data.csv')

In [3]:
blending_materials

    availability      cost     p_max
0    3650.040029  4.996321  0.593264
1    4465.879557  9.605714  0.698169
2    8660.230044  7.855952  0.415004
3    3852.298046  6.789268  0.515288
4    2525.434720  3.248149  0.513329
..           ...       ...       ...
95   6542.650882  5.950365  0.379637
96   6715.842858  6.181863  0.439129
97   1407.736088  5.420328  0.548094
98   4371.513532  2.203353  0.517920
99   6632.739241  2.863131  0.350257

[100 rows x 3 columns]

In [4]:
blending_blends

,quality_1,quality_2,quality_3,quality_4,quality_5,quality_6,quality_7,quality_8,quality_9,quality_10,...,quality_94,quality_95,quality_96,quality_97,quality_98,quality_99,quality_100,demand,quality_min,quality_max
0,80.125450,94.259594,86.347745,66.517377,62.822750,85.696771,61.060452,83.431023,97.609210,83.018967,...,74.825686,92.511983,97.889943,99.440043,90.135127,75.050383,63.340029,112.571674,84.082659,96.420316
1,91.085877,82.336170,76.968880,96.254175,64.447899,79.705004,60.454146,78.746426,62.252131,64.752717,...,86.868027,84.725130,74.326509,64.542304,86.862928,80.812308,90.892736,354.564165,77.395619,90.841400
2,80.806540,94.087260,82.076274,82.437519,95.066144,76.139315,65.360609,61.151307,90.205490,84.812382,...,73.099894,64.790485,95.621091,83.743698,87.164093,91.566850,79.937688,225.742392,76.448949,91.616287
3,63.476812,81.484262,83.473645,89.817579,77.266382,65.103212,71.351036,74.523292,85.836690,82.831132,...,80.108816,69.288508,95.982983,75.355649,81.742114,96.258884,84.969520,303.428276,79.894528,98.985542
4,64.675922,97.593285,85.108322,73.396225,65.570883,91.761008,84.802910,81.338444,95.755703,91.543888,...,98.442813,65.946509,76.584965,63.413987,99.874970,80.087800,83.815401,463.026590,84.856505,96.064291
5,62.683059,89.998419,68.396224,95.922172,68.205586,67.627509,61.461987,78.882678,82.593645,62.628346,...,93.189672,68.256851,60.439833,65.475425,96.000746,94.955603,83.896524,199.716892,77.420553,90.091971
6,84.020674,86.601467,67.014851,96.576478,76.750821,75.325541,80.756708,61.878639,66.651335,89.521345,...,85.035655,95.439110,84.634528,69.318379,60.976031,94.803955,60.850776,264.153169,81.721355,91.014715
7,94.988067,81.157485,97.562708,91.951329,99.917364,74.028473,90.687532,76.077237,79.195025,85.100219,...,82.629279,70.681131,95.145199,91.897041,86.338073,94.023269,94.691768,402.220455,82.616196,96.635018
8,88.334519,93.480533,87.898858,87.205631,84.744455,90.108666,66.344204,95.234830,94.873741,61.169891,...,93.791329,90.440960,85.048813,65.249795,61.301047,96.833914,84.666013,191.519266,77.376375,90.050616
9,91.861492,79.260894,64.692328,65.007432,87.422611,77.212236,68.020989,79.663782,62.568357,83.278856,...,89.086763,89.708261,77.019733,73.837400,74.841551,99.505983,61.604368,130.791964,82.282163,91.608081
10,94.681260,83.147016,77.544617,89.010306,79.466758,94.936930,96.028075,76.868837,71.073112,83.694013,...,77.750009,94.725690,67.085992,87.705038,93.524612,97.784569,87.329921,215.900581,78.677831,95.487338
11,79.886991,84.713890,94.756199,82.824390,61.215482,97.237948,87.581070,87.060535,68.627006,86.355419,...,70.262511,98.517075,79.341826,92.239702,82.009062,61.736501,85.326055,164.488515,81.323058,96.918952
12,98.056134,84.064473,92.767554,95.368259,69.123191,68.481794,84.439240,76.441139,93.594452,96.000925,...,84.943428,63.564977,90.210817,65.108539,93.042705,91.281124,88.349788,471.879061,81.335297,96.519613
13,61.446415,72.125134,70.524503,74.405456,63.505710,97.478313,82.152090,72.220972,75.879261,77.888102,...,60.441251,76.646160,79.253766,60.767691,70.392528,90.411593,65.484388,423.248152,80.357747,92.242693
14,81.412405,68.608075,60.484831,69.648058,99.034950,92.061484,98.383066,79.514162,64.389448,81.918380,...,84.517583,97.723034,69.627708,64.860055,67.898820,95.476996,85.832433,353.361503,75.902898,97.121792
15,71.436272,92.637878,94.454800,93.860574,96.757061,70.089641,90.201677,78.421580,93.679942,89.139627,...,88.307237,91.544599,80.690762,77.607960,65.898101,73.127710,77.360775,448.584236,83.353025,92.372491
16,63.544017,68.824478,83.929012,89.426525,99.933900,97.324533,85.702608,76.849922,85.447095,91.426065,...,64.590755,94.405588,88.912572,62.706734,88.313404,81.741529,63.269014,421.468831,78.207801,93.253997
17,78.332026,79.387851,66.630982,97.827926,93.999015,86.760893,78.491822,76.470622,86.038939,81.817275,...,72.574005,78.846716,92.865476,78.370608,74.311931,79.768498,93.129970,174.628024,76.865185,97.464914
18,73.408322,66.950464,88.480561,93.039129,64.025499,69.594965,65.678880,73.917656,78.014039,89.953053,...,99.817501,94.227844,80.857828,62.545636,93.254941,83.959140,64.597320,457.023599,75.407751,96.496329
19,63.754291,96.385073,86.768011,93.171472,95.159156,82.870894,80.697854,77.217096,72.677864,77.383838,...,74.190852,97.669028,86.742906,87.146798,74.476800,83.746432,60.405247,315.736897,80.908929,98.492234
20,85.443842,96.531478,84.502939,94.947944,88.958922,64.822337,96.098132,62.657754,81.358699,65.685485,...,93.345998,77.617654,72.093330,70.373396,67.784953,62.305903,73.697919,422.976062,81.775644,96.576129
21,70.809908,98.656695,82.308353,73.891082,83.218704,65.567868,77.761750,85.049373,79.555913,76.071152,...,84.544165,63.544189,79.505112,63.105973,76.301721,76.284260,62.640394,458.436520,75.165878,95.683086
22,73.952821,64.439924,92.329408,97.907521,62.892659,98.204608,80.903064,71.982627,63.074483,80.024971,...,85.765969,61.927440,74.402019,98.271993,80.016046,77.309165,78.307984,227.201390,80.120931,90.936748
23,68.355309,74.748287,74.792530,62.094201,90.702705,76.660177,92.887195,94.013920,68.479762,86.294139,...,65.632118,84.896546,91.252874,83.131936,65.878508,92.444951,85.438188,144.020770,77.264958,93.677158
24,75.526628,86.965212,70.396199,73.807688,96.699434,71.620180,78.799531,95.605645,88.308854,62.488129,...,98.037144,83.084903,74.284846,91.501963,70.040055,82.562961,74.343138,191.174065,81.451728,92.652024
25,86.265243,69.615957,67.663718,96.729563,64.072147,80.238316,68.834111,61.557199,61.440753,67.008871,...,88.576967,90.360211,64.100639,80.554179,80.355622,74.771231,97.316995,270.843115,76.743664,92.439896
26,93.100253,87.888375,88.573065,78.468646,96.839781,87.783817,89.159242,94.467636,70.962864,92.282836,...,76.144040,89.515399,88.182177,76.909145,73.860967,75.904495,70.571051,427.205906,81.909377,99.730106
27,68.213318,79.321588,70.741350,71.498467,86.270243,98.741493,84.145488,63.079179,63.023345,98.056929,...,81.533278,70.754141,74.737957,95.813844,86.658522,91.495481,78.173817,444.292233,78.867353,93.930977
28,85.209889,69.935344,88.218433,77.104053,77.701821,85.972893,97.451225,62.560254,92.989729,71.695324,...,87.857192,88.085844,66.867756,80.004510,76.478324,94.821079,85.256757,102.780852,84.367300,98.920466
29,81.300163,64.615786,84.225516,64.688156,73.488263,65.713679,87.682946,68.250085,75.674375,95.826991,...,66.259069,78.956849,88.655884,70.837708,68.090167,72.553072,69.660025,304.298921,76.375209,96.311386
30,68.596505,76.994034,96.313541,80.282386,67.516815,63.078867,87.846246,75.311951,92.873238,86.380431,...,99.825244,99.244716,85.980357,92.176562,88.604006,83.726329,62.133920,266.964401,78.410664,97.948113
31,78.190574,86.991452,87.101265,74.924905,97.667679,66.694281,80.014378,87.635359,87.885432,85.945558,...,73.705806,94.586357,66.197012,63.309473,79.381520,72.096780,82.536335,188.843124,76.134735,95.026371
32,92.152196,65.485940,83.227963,80.220350,65.763151,84.959939,70.945617,79.513373,63.290893,78.383362,...,78.651977,90.423026,66.179688,79.490614,77.199409,83.876428,99.982308,147.946147,84.246936,95.769039
33,90.777956,75.914628,93.102122,66.828335,61.218547,68.177935,73.616462,80.423230,84.605166,96.424229,...,62.224221,60.275118,68.497891,86.540944,76.447900,76.096250,95.383476,235.046069,83.773394,94.925177
34,95.822514,96.367011,72.555123,87.642233,70.865327,67.624393,67.385298,73.684305,77.198305,93.237967,...,76.309924,66.448752,86.256384,98.846036,82.487552,88.590131,62.738018,477.163882,77.579416,91.952430
35,76.706680,64.654339,84.511833,97.539286,86.471109,63.072122,74.186648,82.026535,76.128310,93.345760,...,75.724156,64.009823,60.663699,86.468747,84.097978,66.520765,69.352513,229.281173,81.599840,97.224521
36,60.948310,93.397888,98.987624,65.418381,69.259009,94.736381,97.058552,76.785095,62.024899,61.575673,...,84.775599,76.447619,77.099458,73.211387,82.569273,94.022981,68.061135,307.516249,83.172222,92.807724
37,97.377322,87.563506,92.930929,82.247628,91.180668,60.648016,92.735217,61.605554,95.596535,99.678510,...,93.260733,96.735902,85.991522,64.137365,76.081089,89.157568,91.192835,381.207584,80.552008,90.243160
38,64.728745,60.001229,88.485482,74.263847,70.179253,60.515899,81.611976,94.046029,98.305266,82.629798,...,78.167347,76.491189,97.389197,70.035164,64.817894,83.381725,98.772872,245.451841,80.296506,96.454723
39,75.113569,62.481471,73.572211,80.237266,66.476920,86.324089,99.909976,78.069579,74.189142,76.028167,...,93.053632,83.520019,74.124116,91.991335,82.187481,93.037292,85.258352,488.712833,77.418523,91.771107
40,91.376219,83.942520,76.565643,98.317834,81.644553,84.203581,68.819506,85.026032,82.864306,67.393536,...,75.973303,76.386915,99.128827,67.235676,91.966319,73.367709,89.234814,484.978918,75.931028,99.404586
41,76.800440,83.134391,93.304471,92.166623,94.656927,62.384693,87.682022,65.599495,76.632743,81.943537,...,71.331376,76.012513,92.474645,60.554485,85.975153,86.755061,91.946231,200.712918,83.972158,99.539286
42,97.310118,60.805514,66.151348,95.446852,78.340742,82.583626,86.521088,87.162664,97.269616,99.877977,...,65.267476,88.201636,89.679109,87.108930,70.092589,94.921726,66.754339,298.899402,84.004181,99.148644
43,62.145392,88.698600,79.019029,93.963921,75.335886,66.731144,93.457688,81.956385,67.567832,88.815360,...,99.773212,69.309134,62.153221,67.595013,61.558314,75.672436,92.096071,220.351324,81.331015,93.701587
44,73.649778,77.767336,87.023471,80.355763,94.457827,94.641427,60.396428,91.121852,78.429344,99.553622,...,61.724004,67.163798,75.688712,97.911188,65.647963,90.540634,64.347302,213.936198,78.390298,90.154566
45,99.250303,75.264660,91.009382,73.703643,85.106755,67.680643,65.840841,97.522566,96.705891,95.498758,...,74.530214,91.757405,97.639693,84.928415,89.665091,92.203892,93.801586,114.754779,78.492096,99.283186
46,75.802134,62.050538,76.075051,86.950249,78.014015,89.958526,74.279297,85.389766,67.456792,89.974777,...,86.667426,84.935183,84.098767,79.591435,81.146264,73.377701,80.772508,343.825734,82.259557,94.281841
47,67.902236,92.206976,67.431078,63.398652,77.449841,86.332298,77.508673,71.070165,82.326847,73.880093,...,90.653889,76.256661,95.193510,85.947318,95.969957,84.940212,65.251519,301.071609,83.971103,99.666548
48,72.387668,68.071798,96.353060,90.416003,87.055935,72.038653,67.361791,90.258044,78.966318,69.031582,...,96.397206,88.690475,83.282805,91.912187,94.574651,78.275523,79.004335,120.591500,83.870864,99.636200
49,75.442037,98.668246,87.886650,63.328923,94.518385,79.222398,62.750156,81.988690,76.686571,95.109976,...,66.457907,98.429852,81.501606,60.567865,70.305280,77.997747,87.716356,211.458586,82.798755,98.530095

#What do the decision variables represent and how many of them are there?